version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      DB_HOST: '${DB_HOST}'
      DB_NAME: '${DB_DATABASE}'
      DB_USER: '${DB_USERNAME}'
      DB_PASS: '${DB_PASSWORD:-secret}'
    depends_on:
      - db

  db:
    image: 'postgres:15-alpine'
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - 'dev-db-data:/var/lib/postgresql/data'

  adminer:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    depends_on:
      - db
    ports:
      - "5050:5050"

volumes:
  dev-db-data: